local highlights = {
	Bold = { style = "bold" },
	Boolean = { fg = C.primary_blue },
	Character = { fg = C.red },
	ColorColumn = { bg = C.background },
	Comment = { fg = C.comment, style = "italic" },
	Conceal = { fg = C.foreground }, -- TODO
	Conditional = { fg = C.primary_blue },
	Constant = { fg = C.primary_blue },
	CursorColumn = { bg = C.background2 },
	Cursor = { fg = C.cursor_fg, bg = C.cursor_bg },
	CursorIM = { fg = C.cursor_fg, bg = C.cursor_bg },
	CursorLine = { bg = C.background },
	CursorLineNr = { fg = C.primary_blue, style = "bold" },
	Debug = { fg = C.red },
	Define = { fg = C.primary_pink },
	Delimiter = { fg = C.comment },
	DiffAdd = { fg = C.background, bg = C.red },
	DiffChange = { fg = C.background, bg = C.turk, style = "underline" },
	DiffDelete = { fg = C.background, bg = C.red },
	Directory = { fg = C.primary_blue },
	EndOfBuffer = { fg = C.background },
	Error = { fg = C.red, bg = C.background, style = "bold" },
	ErrorMsg = { fg = C.red, bg = C.background, style = "bold" },
	Exception = { fg = C.red },
	FloatBorder = { fg = C.primary_purple, bg = C.background },
	Float = { fg = C.turk },
	FoldColumn = { fg = C.foreground, bg = C.background },
	Folded = { fg = C.foreground, bg = C.background },
	Function = { fg = C.yellow },
	Identifier = { fg = C.primary_blue },
	Ignore = { fg = C.primary_blue, bg = C.background, style = "bold" },
	Include = { fg = C.primary_purple },
	IncSearch = { fg = C.orange, bg = C.light_gray },
	Italic = { style = "italic" },
	Keyword = { fg = C.primary_blue },
	Label = { fg = C.primary_purple },
	lCursor = { fg = C.cursor_fg, bg = C.cursor_bg },
	LineNr = { fg = C.primary_blue },
	Macro = { fg = C.primary_purple },
	MatchParenCur = { style = "underline" },
	MatchParen = { fg = C.hint_blue, bg = C.background, style = "underline" },
	MatchWordCur = { style = "underline" },
	MatchWord = { style = "underline" },
	ModeMsg = { fg = C.foreground, bg = C.background },
	MoreMsg = { fg = C.red },
	MsgArea = { fg = C.foreground, bg = Config.transparent_background and "NONE" or C.background },
	MsgSeparator = { fg = C.foreground, bg = C.background },
	NonText = { fg = C.background },
	Normal = { fg = C.foreground, bg = Config.transparent_background and "NONE" or C.background },
	NormalFloat = { bg = C.background },
	NormalNC = { fg = C.foreground, bg = Config.transparent_background and "NONE" or C.background },
	Number = { fg = C.turk },
	Operator = { fg = C.foreground },
	Pmenu = { fg = C.light_gray, bg = C.background2 },
	PmenuSbar = { bg = C.background },
	PmenuSel = { bg = C.primary_blue },
	PmenuThumb = { bg = C.comment },
	PreCondit = { fg = C.primary_purple },
	PreProc = { fg = C.primary_purple },
	Question = { fg = C.red },
	QuickFixLine = { bg = C.primary_blue },
	Repeat = { fg = C.primary_purple },
	Search = { fg = C.light_gray, bg = C.hint_blue },
	SignColumn = { bg = C.background },
	SpecialChar = { fg = C.foreground },
	SpecialComment = { fg = C.comment },
	Special = { fg = C.red },
	SpecialKey = { fg = C.primary_blue, style = "bold" },
	SpellBad = { fg = C.red, style = "underline" },
	SpellCap = { fg = C.yellow, style = "underline" },
	SpellLocal = { fg = C.comment, style = "underline" },
	SpellRare = { fg = C.comment, style = "underline" },
	Statement = { fg = C.primary_purple },
	StorageClass = { fg = C.primary_blue },
	String = { fg = C.red },
	Structure = { fg = C.primary_blue },
	Substitute = { fg = C.light_gray, bg = C.orange },
	TabLine = { fg = C.light_gray, bg = C.background },
	TabLineFill = { fg = C.background, bg = C.background },
	TabLineSel = { fg = C.foreground, bg = C.background },
	Tag = { fg = C.primary_blue },
	TermCursor = { fg = C.cursor_fg, bg = C.cursor_bg },
	TermCursorNC = { fg = C.cursor_fg, bg = C.cursor_bg },
	Title = { fg = C.primary_blue, style = "bold" },
	Todo = { fg = C.magenta, bg = C.background, style = "bold" },
	Typedef = { fg = C.primary_blue },
	Type = { fg = C.primary_blue },
	Underlined = { style = "underline" },
	Variable = { fg = C.primary_blue },
	VertSplit = { fg = C.primary_purple, bg = C.background },
	Visual = { bg = C.primary_blue },
	VisualNOS = { bg = C.background },
	WarningMsg = { fg = C.primary_purple, bg = C.background },
	Whitespace = { fg = C.background },
	WildMenu = { fg = C.foreground, bg = C.primary_blue },
}
return highlights
